name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test-all
