name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Test
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-all
